version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/test
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 10
      runas: root
