version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/test
hooks:
  AfterInstall:
    - location: stop.sh
      runas: root
  ApplicationStart:
    - location: start.sh
      runas: root
